[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

# Evita cache agressivo do script.js durante testes
[[headers]]
  for = "/script.js"
  [headers.values]
    Cache-Control = "no-cache"
